grpc:
  server:
    port: 50051
pm:
  pdp:
    resource:
      admin-hostname: localhost
      admin-port: 50052
    esdb:
      hostname: localhost
      port: 2113
      event-stream: pm-events-v1
      snapshot-stream: pm-snapshot-v1
    plugins:
      dir: "./plugins"
logging:
  level:
    root: INFO
management:
  health:
    neo4j:
      enabled: false